name: Optimize Images with WebP

on:
  push:
    branches: [main]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install img2webp
        run: go install github.com/adnenre/img2webp@latest

      - name: Run img2webp
        run: |
          img2webp \
            --input "./public" \
            --q "85" \
            --replace "true" \
            --dry-run "false"
