name: Test img2webp Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: adnenre/img2webp@v0.2.0
        with:
          input-dir: "./public"
      - run: |
          ls public/*.webp
          grep "\.webp" public/index.html
